### ISSUE TITLE
where can I download this file “/bounce/prt_data.mat”

### ISSUE THREAD

**Issue by hanchaoyuan** [ZhengZerong/PaMIR#18]
FileNotFoundError: [Errno 2] No such file or directory: '../dataset_example/mesh_data/./0000/bounce/prt_data.mat'

**Comment by 2579690686** [comment]
have you solved the problem?

**Comment by 2579690686** [comment]
because main_calc_prt.py is not successfully run.

**Comment by rabl-rabl** [comment]
How should I modify to properly run main_calc_prt.py?
