### ISSUE TITLE
how to generate tetrahedron related data from SMPLX?

### ISSUE THREAD

**Issue by YuliangXiu** [ZhengZerong/PaMIR#2]
Hi Zerong

Could you provide some references to show how to generate these two files from SMPL model?

[tetrahedron.txt](https://github.com/ZhengZerong/PaMIR/blob/a52c4360731d9aae6876c38479df43025241d465/networks/util/util.py#L67)

[tetra_smpl.npy](https://github.com/ZhengZerong/PaMIR/blob/a52c436073/networks/evaluator.py#L49)

Thanks a lot

**Comment by MrChangJiang** [comment]
> 
Hello, how did you solve this problem in the end?

**Comment by MrChangJiang** [comment]
> Hi Zerong
> 
> Could you provide some references to show how to generate these two files from SMPL model?
> 
> [tetrahedron.txt](https://github.com/ZhengZerong/PaMIR/blob/a52c4360731d9aae6876c38479df43025241d465/networks/util/util.py#L67)
> 
> [tetra_smpl.npy](https://github.com/ZhengZerong/PaMIR/blob/a52c436073/networks/evaluator.py#L49)
> 
> Thanks a lot
Hello, how did you solve this problem in the end

**Comment by YuliangXiu** [comment]
@MrChangJiang Please check [here](https://github.com/YuliangXiu/ICON/tree/master/scripts/tetrahedronize_scripts).

**Comment by MrChangJiang** [comment]
Thank you very much. Your work on ICON is great!
